name: Réalisation de tests lors de la création d'une pull request

# Tests réalisés sur les pull requests sur la branche main
on: 
    pull_request:
        branches: [ "main" ]
        types: [ opened ]

# Pour l'instant rien de particulier n'est fait, on spécifie juste que les tests tournent sur Ubuntu
jobs:
    uv_opened_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 # Permet d'accéder aux fichiers du dêpot

            - uses: actions/setup-python@v5 # Installe python 3.13
              with:
                python-version: '3.13'

            - uses: astral-sh/setup-uv@v3 # Installe uv
              with:
                version: "latest"

            - run: uv sync # Installe les dépendances
            - run: uv build # Compile le projet
            - run: uv run pytest tests/ # Lance les tests compris dans le dossier tests